### ISSUE TITLE
Exception has occurred: ModuleNotFoundError

### ISSUE THREAD

**Issue by zisco67** [m-click/requests_pkcs12#38] opened 2023-01-25 13:32 UTC
Line `from requests_pkcs12 import get,post` raises that exception, and altough I've tried several hints, they all don't work:
`No module named 'cryptography.hazmat.backends.openssl.x50`
I'm running python in a venv, no warnings during `pip install` - any ideas?

**Comment by vog** [comment] 2023-01-25 13:42
This is a duplicate of #36 which has been fixed in the meantime.

Please try again requests_pkcs12 version 1.15 or later:

* https://pypi.org/project/requests-pkcs12/

In case this doesn't fix your problem, please feel free to open a new issue that contains more details.

**Closed as completed by vog** 2023-01-25 13:42 UTC
