### ISSUE TITLE
ImportError: cannot import name 'PyOpenSSLContext'

### ISSUE THREAD

**Issue by kpkaur28** [m-click/requests_pkcs12#14] opened 2019-09-24 02:35 UTC
```
ImportError: cannot import name 'PyOpenSSLContext'
```

when i try to use this library. Can anyone help me with the fix? I cant find PyOpenSSLContext anywhere online.

```
>>> from requests_pkcs12 import Pkcs12Adapter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\requests_pkcs12.py", line 24, in <module>
    from requests.packages.urllib3.contrib.pyopenssl import PyOpenSSLContext
ImportError: cannot import name 'PyOpenSSLContext'
```

**Comment by vog** [comment] 2019-09-24 09:30
Unfortunately I can't reproduce the issue. Please be more specific about your setup.

This is how I tested it:

I created a fresh Python3 environment where I installed `requests_pkcs12` (and automatically its dependencies such as `requests`):

```
mkdir test
cd test
python3 -m virtualenv -p python3 .venv
pipenv install requests_pkcs12
pipenv run python3
```

The final command runs a Python session in which everything looks fine:

```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests_pkcs12 import Pkcs12Adapter
>>> Pkcs12Adapter
<class 'requests_pkcs12.Pkcs12Adapter'>
```

**Comment by kpkaur28** [comment] 2019-09-24 21:19
For my setup, i am trying to get access to a website that requires certificates. One liner code: 
response = get('https://<web_link>', pkcs12_filename=<file>, pkcs12_password="") 
It works in Python shell. 
However, does not work in Windows command prompt or Windows Powershell.

**Comment by vog** [comment] 2019-10-04 09:28
Thanks for the additional information. This confirms that it is indeed a problem with your Python setup, and that there is nothing we can do inside libraries like `requests` or `requests_pkcs12` to solve this issue.

Perhaps your cmd.exe (Windows command prompt) and Powershell have different environment variables that prevent Python from finding its SSL libraries. I propose to compare the value of the `PYTHONPATH` environment variable in your different environments (cmd.exe, Poweshell, Python shell).

Closing this issue for now, as it has nothing to do with the `requests_pkcs12` library.

**Closed as completed by vog** 2019-10-04 09:28 UTC
Labels: wait for feedback
